### PR TITLE
Proxy_issue

### PR DESCRIPTION
**Pull request by Abdeluswho**

### CODE REVIEW

**Comment by Gerardofer** [comment]
Hey Sofiane, sorry to come to this now.  There seem to be some issues with your PR, would you be able to see what the issue is and resolve it?  I think the proxy file I had created is enough, so you can just keep that file, just take a look a the other files to solve conflicts.

**Comment by Abdeluswho** [comment]
Sure! I will take a look in the afternoon.

**Comment by Abdeluswho** [comment]
I think the other conflicts besides the proxy are the dependencies in the package-lock.json file which I don't know much about! do you think if I just delete it it will solve the prob?

**Comment by Gerardofer** [comment]
PR has issues with the jason-package.json

**Pull request closed without merging**
